name: "CodeQL Analysis"

on:
  push:
    branches: [ "main" ]   # Lance l'analyse à chaque push sur main
  pull_request:
    branches: [ "main" ]   # Lance aussi à chaque Pull Request
  schedule:
    - cron: '0 2 * * *'    # (Optionnel) Scan automatique chaque jour à 02h00 UTC

jobs:
  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write   # Nécessaire pour publier les résultats

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]  
        # ⚠️ Mets ici les langages que tu veux analyser
        # Exemples possibles : javascript, python, java, cpp, csharp, go, ruby

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
